adding FWF export,
tuwien-csd/damap-backend pull request #36
Opened 2022-07-22 15:43 UTC by ZenoLC

* refactoring science europe template

refs #77606, #77607, #79403

2022-07-22 15:43 UTC, ZenoLC commented
currently hardcoded to export FWF document, 
adaptive system still pending.

2022-07-26 16:13 UTC, clarascu requested changes
It might be helpful to rename `DocumentConversionService`, `AbstractExportTemplate` & `ScienceEuropeComponents` to better capture their purpose.

2022-07-26 16:13 UTC, clarascu commented on src/main/java/at/ac/tuwien/damap/conversion/ExportFWFTemplate.java
> +    TemplateFileBrokerService templateFileBrokerService;
Same variable as in `AbstractExportTemplate` (see sonar analysis).

2022-07-26 16:13 UTC, clarascu commented on src/main/java/at/ac/tuwien/damap/conversion/AbstractExportTemplate.java
> +    protected final SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
Same variable as in `DocumentConversionService` (see sonar analysis).

2022-08-02 16:00 UTC, ZenoLC commented
classes were renamed to better reflect their functionality.

2022-08-03 13:12 UTC, clarascu approved these changes

2022-08-03 13:19 UTC, merged