Reusable base service
tuwien-csd/damap-backend pull request #64
Opened 2022-11-30 12:15 UTC by rekt-hard

closes GH-63 

provide basic interfaces for resources and services.

2022-11-30 12:16 UTC, rekt-hard commented
Currently, only person specific adaptions have taken place. If the changes are accepted, project specific adaptions will be performed.

2022-12-13 08:16 UTC, rekt-hard commented
@ZenoLC : Should the search method on the service level only have one parameter (query parameters) and then let the implementation decide what to do? Creating a `Search` object seems like putting logic in the resource layer, when it should really be in the service layer (i.e. defining endpoints and parameters vs implementing logic).

2022-12-13 09:02 UTC, ZenoLC commented
Yes, you are right, since we are not sending the additional information to the frontend we can just defer to the implementations discretion.

2023-02-02 14:15 UTC, rekt-hard commented
Rebased the branch on `next`

2023-02-15 15:50 UTC, ZenoLC requested changes
Looks good and works fine. 
Only thing missing is to remove the assigning of ORCID-ID to uni-ID
And wait for frontend changes approval.

This changes the current behavior, in which a default list of projects is loaded initially. I personally would bring that back, as an additional check, but it is not within the scope of this PR, and will be made its own task.

2023-02-15 15:50 UTC, ZenoLC commented on src/main/java/at/ac/tuwien/damap/rest/persons/orcid/ContributorORCIDExpandedSearchMapper.java
> +        contributorDO.setUniversityId(contributor.orcidId);
please remove this before merge, as discussed previously

2023-02-15 16:21 UTC, ZenoLC approved these changes
nice

2023-03-01 13:41 UTC, merged